# fly.toml app configuration file generated for backend-mern-todo on 2024-07-29T04:33:16+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-mern-todo'
primary_region = 'sin'

[build]

[env]
  ACCESS_TOKEN_SECRET = 'bagusasp01'
  MONGO_CONNECTION_STRING = 'mongodb+srv://bagusasp01:bagusasp01@tugasweboop.grjypnb.mongodb.net/?retryWrites=true&w=majority&appName=tugasWebOOP'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
